### ISSUE TITLE
Controller Emulation Partially Broken

### ISSUE THREAD

**Issue by GlacialTurtle** [kozec/sc-controller#105]
Tested with latest stable and git, left analogue stick emulation seems to break the mouse, causing it to flicker/disappear and moving rapidly. Other inputs seem to not respond, though they register correctly in SC test mode.

I tested in the Dolphin emulator controller settings dialogue which shows controller inputs, It only seemed to properly register input from the triggers and analogue sticks, no buttons worked.

Also tested in Aragami (Unity engine), where the mouse constantly recenters and flickers even when not moving the analog stick and inputs besides WASD and analogue stick don't register.

Edit: scratch that, Aragami works OK besides mouse issue.

Edit 2: lol nope, all sorts of weirdness. In-game controls work sort of aside from mouse issue, menus flicker back and forth between controller and mouse prompts, keyboard inputs are blocked when in menus. This is even with thee controller turned off.

**Comment by kozec** [comment]
Is there any chance you are getting X11 mouse emulation on top of joystick emulation? [X has driver that allows you to control mouse](https://github.com/kozec/sc-controller/issues/97#issuecomment-252410192) with any connected joystick that started to pickup virtual gamepad from SCC lately, for completely` unknown reason...

**Comment by GlacialTurtle** [comment]
I checked and I don't seem to have that installed (xserver-xorg-input-joystick, Ubuntu 16.04). Trying out the X config that was suggested regardless in that bug report also meant Ubuntu couldn't boot properly so I removed it again.

I just noticed the mouse seems to disappear when using the left analog stick (set to dpad) and right pad too, though it doesn't move the mouse rapidly around.

**Comment by kozec** [comment]
Ok, I should have Ubuntu 16.04 somewhere around here...

When you say mouse disappears, you mean it moves out from screen, or just that cursor is no longer drawn?

**Comment by GlacialTurtle** [comment]
Yes, most inputs seem to register (jstest-gtk), mouse still goes crazy (not drawn/flickers and moves around rapidly).

**Comment by kozec** [comment]
It looks like I'll really have to blame this to ubuntu somehow :D

@GlacialTurtle , can you test something for me?

While that problem is happening, try running `xinput` command and check if it outputs something like this:

```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ USB Optical Mouse                       	id=8	[slave  pointer  (2)]
⎜   ↳ SIGMACHIP USB Keyboard                  	id=10	[slave  pointer  (2)]
⎜   ↳ SCController Mouse                      	id=13	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Power Button                            	id=7	[slave  keyboard (3)]
    ↳ SIGMACHIP USB Keyboard                  	id=9	[slave  keyboard (3)]
    ↳ SCController Keyboard                   	id=12	[slave  keyboard (3)]
    ↳ Microsoft X-Box 360 pad (keys)          	id=14	[slave  keyboard (3)]
```

then try running `xinput test 'SCController Mouse'` and check if it outputs any events when it shouldn't (ie when SCC is set to emulate controller)

And, by the way, if there **is** _Microsoft X-Box 360 pad_ listed under _Virtual core pointer_, then that's your problem.

**Comment by GlacialTurtle** [comment]
This is the output I get when I try those commands:

 ```
xinput
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ ROCCAT ROCCAT Lua                       	id=8	[slave  pointer  (2)]
⎜   ↳ HID 04f3:0103                           	id=10	[slave  pointer  (2)]
⎜   ↳ Microsoft X-Box 360 pad                 	id=15	[slave  pointer  (2)]
⎜   ↳ SCController Mouse                      	id=16	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Power Button                            	id=7	[slave  keyboard (3)]
    ↳ HID 04f3:0103                           	id=9	[slave  keyboard (3)]
    ↳ Skullcandy Skullcandy Slayer            	id=11	[slave  keyboard (3)]
    ↳ Eee PC WMI hotkeys                      	id=13	[slave  keyboard (3)]
    ↳ SCController Keyboard                   	id=14	[slave  keyboard (3)]
```

For `xinput test 'SCController Mouse'` I don't get any output while set to controller emulation, but do when set to a M&KB bind and move the mouse as you'd expect. I still get the same issue though.

To be more precise, in case it helps, I noticed the mouse only seemingly moves rapdily when moving whatever is set to the left stick. Left stick, right stick and analogue trigger bindings all make the mouse disappear.

Disabling the 360 pad causes the face buttons and bumpers to not register in applications (they still highlight in SC Controller when pressed though). In Dolphin for example in the controller settings panel they show up as always pressed (highlighted red). The mouse/analogue issue is fixed however when I do that.

**Comment by kozec** [comment]
Ok and are you really _sure_ that you don't have `xf86-input-joystick` installed? Because according to this bug - https://bugs.freedesktop.org/show_bug.cgi?id=42399 - this is exactly what's that module is supposed to do - so gamepad controlling mouse it's not a bug, it's a feature.

In theory, `xinput float "Microsoft X-Box 360 pad"` should disconnect emulated pad from mouse without disabling it entirely for XI2 applications.

**Comment by GlacialTurtle** [comment]
I'm sure that it's not installed - running `sudo apt purge xserver-xorg-input-joystick` just tells me it isn't installed.

`xinput float "Microsoft X-Box 360 pad"` does seem to work. Just tested it in Dolphin both in controller setup UI and in-game and buttons and analogue stuff all seem OK, no weird mouse issue.

**Comment by kozec** [comment]
> xinput float "Microsoft X-Box 360 pad" does seem to work. Just tested it in Dolphin both in controller setup UI and in-game and buttons and analogue stuff all seem OK, no weird mouse issue.

Great, I'll try to add whatever it does to scc-daemon, so it will be done automatically.

**Comment by japrogramer** [comment]
I have the same problem. 
xinput output:
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ Blue Microphones Yeti Stereo Microphone 	id=13	[slave  pointer  (2)]
⎜   ↳ USB OPTICAL MOUSE                       	id=14	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Power Button                            	id=7	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=8	[slave  keyboard (3)]
    ↳ SINO WEALTH USB KEYBOARD                	id=9	[slave  keyboard (3)]

whats weird is that the buttons work to bring up the onscreen menu and in the onscreen keyboard i can see that the pads are responsive but i don't have control of the mouse or any button i assign to it works
    ↳ SINO WEALTH USB KEYBOARD                	id=10	[slave  keyboard (3)]

**Comment by kozec** [comment]
@japrogramer You have same problem, but no scc-related device is listed in xinput? How's that even possible?

**Comment by japrogramer** [comment]
well i can not control the mouse, even tho my profile was setup to do that. also they presses i programed in weren't being registered. even so i can pull up the scc menu with the menu button, and in the menu all keys work, but i still can't control the mouse or keyboard. The xinput output suggest that no keyboard mouse controllers are being created but no errors of the kind are being reported by the daemon, it reports success.

> D SCCDaemon     Starting SCCDaemon...
D SCCDaemon     Initializing drivers...
D USB           Registered hotplug USB driver for 28de:1102
D USB           Registered hotplug USB driver for 28de:1142
D Mapper        Creating virtual devices
D Mapper        Keyboard: <scc.uinput.Keyboard object at 0x7f4e75b4ac10>
D Mapper        Mouse:    <scc.uinput.Mouse object at 0x7f4e75adda90>
D Mapper        Gamepad:  <scc.uinput.UInput object at 0x7f4e75af1150>
[<Keys.BTN_RIGHT: 273>]
(50, 254)
I profile       Converted button(Keys.BTN_RIGHT) to trigger(50, button(Keys.BTN_RIGHT))
[<Keys.BTN_LEFT: 272>]
(50, 254)
I profile       Converted button(Keys.BTN_LEFT) to trigger(50, button(Keys.BTN_LEFT))
D SCCDaemon     Created control socket /home/archangel/.config/scc/daemon.socket
D SCCDaemon     Connected to XServer :0

(scc-osd-daemon.py:3904): Gtk-WARNING **: Theme parsing error: gtk.css:2554:8: not a number

(scc-osd-daemon.py:3904): Gtk-WARNING **: Theme parsing error: gtk.css:2554:17: Using Pango syntax for the font: style property is deprecated; please use CSS syntax
D OSD DaemonCtrlr   Connected to daemon, version 0.3
D OSD DaemonCtrlr   Daemon reported profile change: /home/archangel/.config/scc/profiles/Browsing.sccprofile
D OSD DaemonCtrlr   Daemon is ready.
I SCCDaemon     Registered scc-osd-daemon
I OSD osd.daemon    Sucessfully registered as scc-osd-daemon

**Comment by Occisor** [comment]
Same problem after update. Linux Mint 18 64-bit.
>$ xinput 
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ SteelSeries SteelSeries Rival 100 Dell China	id=8	[slave  pointer  (2)]
⎜   ↳ Thermaltake Tt eSPORTS Challenger Pro gaming keyboard	id=10	[slave  pointer  (2)]
⎜   ↳ Microsoft X-Box 360 pad                 	id=13	[slave  pointer  (2)]
⎜   ↳ SCController Mouse                      	id=14	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Power Button                            	id=7	[slave  keyboard (3)]
    ↳ Thermaltake Tt eSPORTS Challenger Pro gaming keyboard	id=9	[slave  keyboard (3)]
    ↳ ASUS USB2.0 Webcam                      	id=11	[slave  keyboard (3)]
    ↳ SCController Keyboard                   	id=12	[slave  keyboard (3)

All games that support gamepad (X360) now it is not working with steam controller.

**Comment by kozec** [comment]
@japrogramer and @Occisor, can you, please, try that `xinput float "Microsoft X-Box 360 pad"` command as well? If it helps, you really have same problem and I just fixed it (hopefully), otherwise it may be similar, but different problem.

**Comment by Occisor** [comment]
I tried (`xinput float "Microsoft X-Box 360 pad"`), command is worked. But the problem remains.
Also, after update when the program starts always arises a problem in the [screenshot](https://drive.google.com/open?id=0ByLNn3CIHSw_QmFtdU0ta2wtb3c). Steam and other programs except "sc controller" is not running. After 2-3 click on the "Emulation Enable" emulation is started with green light.
I'm back to v.2.17 and all works fine.

**Comment by kozec** [comment]
> I tried (xinput float "Microsoft X-Box 360 pad"), command is worked. But the problem remains.

Sorry, I cannot quite parse this...

> Steam and other programs except "sc controller" is not running. After 2-3 click on the "Emulation Enable" emulation is started with green light.

That sounds like you just had old instance of scc-daemon running. I've just added [new release with fix from this issue](https://github.com/kozec/sc-controller/releases/tag/v0.3.1) and another one Ubuntu/Mint specific problem with udev. I also tested it on fresh install of Mint Cinnamon 18 and it looks OK.

Please, try to update to that release, make sure that there is no process starting with `scc-` running (maybe restart your machine, or at least reload udev rules) and try it again.
