### ISSUE TITLE
Support other controllers?

### ISSUE THREAD

**Issue by LiamDawe** [kozec/sc-controller#145]
I know this project is supposed to be for the Steam Controller, but do you have plans to expand it for others? Steam itself has been updated to support DS4, Xbox 360 and other controllers now too.

**Comment by jrial** [comment]
As far as I know, Steam doesn't offer functionality to remap those controllers though.

Have you looked at [Antilmicro](https://github.com/AntiMicro/antimicro) yet?

**Comment by LiamDawe** [comment]
Yes, Steam does. I said that in the text of the issue itself ;)

**Comment by larsiusprime** [comment]
Context:
http://steamcommunity.com/groups/SteamClientBeta/announcements/detail/586991182161672256

**Comment by kozec** [comment]
Yes, I already thought about it, but placed in in long, realy long-term plan, because it's kinda crazy task to do.

In theory, you can talk to any controller* using HID and thus use it as "input" for SCC, but:
- Driver has no idea which button is which and which axis is which, so user would have to do something [like Steam does when generic controller is used](http://imgur.com/a/0da7g).
- Even if configured, most of normal contollers doesn't have pads, so it would be hard to use SCC profiles with them.

And that last problem kinda beats the purpose :(

* xbox pad is of course exeception from this -_-

**Comment by LiamDawe** [comment]
With the new pre-release, I gave it a test from the AppImage with my Logitech F310 and it wouldn't go past the screen where I select the layout, here's the terminal output:

https://pastebin.com/hm9ych9i

**Comment by kozec** [comment]
Looks like it can't find itself inside of appimage :( And I though I tested it with everything...

**Comment by kozec** [comment]
> With the new pre-release, I gave it a test from the AppImage with my Logitech F310 and it wouldn't go past the screen where I select the layout, here's the terminal output:
> 
> https://pastebin.com/hm9ych9i

Ok, it should be fixed in latest pre-release

**Comment by Sotneo** [comment]
SC-controller can't detect Defender Scorpion X7(xbox 360 like). Detected as Bus 001 Device 012: ID 1345:6006 Sino Lite Technology Corp. Defender Wireless Controller
lsusb -vv -s 1:12: [https://pastebin.com/vFALdev7](https://pastebin.com/vFALdev7)
Controller is working with steam after `xboxdrv --device-by-path 001:012 --type xbox360 --silent`
dmesg:
[  +3,299753] usb 1-1.3.4.1.3: new full-speed USB device number 13 using xhci_hcd
[  +0,125619] usb 1-1.3.4.1.3: New USB device found, idVendor=1345, idProduct=6006
[  +0,000008] usb 1-1.3.4.1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  +0,000005] usb 1-1.3.4.1.3: Product: USB Controller
[  +0,000003] usb 1-1.3.4.1.3: Manufacturer:  
[  +0,000004] usb 1-1.3.4.1.3: SerialNumber: CF8F5200
[окт 3 16:36] input: Xbox Gamepad (userspace driver) as /devices/virtual/input/input29
Is it possible work with other userspace drivers like xboxdrv?

**Comment by kozec** [comment]
SC-Controller works with HID devices and xbox controller nor it likes is not one, so it's most likely not going to work. It may work through evdev, if xboxdrv doesn't prevent that.

**Comment by Sotneo** [comment]
xboxdrv created evdev device, but I can't see it at "Controller registration":

```
sot@sot-MateBook-HZ-W19:~$ python
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import evdev
>>> devices = [evdev.InputDevice(fn) for fn in evdev.list_devices()]
>>> for device in devices:
...   print(device.fn, device.name, device.phys)
... 
('/dev/input/event18', 'Xbox Gamepad (userspace driver)', '')
('/dev/input/event21', 'Microsoft X-Box 360 pad', '')
>>> 

```

**Comment by kozec** [comment]
> xboxdrv created evdev device, but I can't see it at "Controller registration":

But it created virtual device without physical address. Thing is, you are trying to use two different user-space drivers to do same thing with same controller and I'm afraid that's going to clash in new and unexplored ways... What's the point of xboxdrv there? Doesn't kernel and/or evdev have support for that controller?

**Comment by Sotneo** [comment]
Controller don't have mode switch. Kernel(usbhid, joydev, xpad) and/or evdev can't detect the controller.
I understand that it is strange thing. However, why sc-controller care about physical address? Steam don't care about it. 
xboxdrv supports big number of controllers, but don't have profile manager and customization for keys. 
I think, It is not bad idea to support xboxdrv in future.

**Comment by kozec** [comment]
Two reasons. 1st, sc-controller uses hw address to get HID descriptor from kernel and 2nd, sc-controller creates exactly same virtual "Microsoft X-Box 360 pad" with no hw address as output, so those are filtered-out.

Because if you somehow managed to hook sc-controller's output to sc-controller's input, it would be really hard to get it out of resulting never-ending loop :D

**Comment by kozec** [comment]
Done and released, twice :)

**Comment by Jimi-James** [comment]
I just upgraded to 0.4.2 and I still can't get my 2nd generation DS4 connected over bluetooth, but I suspect that might be because of #364.
